# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            GoProject
tagline:          'A Jekyll theme'
description:      'PFC sobre la creación de una plataforma online de Go utilizando <a href="https://www.meteor.com/" target="_blank">Meteor</a>.'
url:              http://goproject.meteor.com
baseurl:          /

author:
  name:           'Víctor Manuel González Mira'
  url:            https://twitter.com/_shadowlink_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shadowlink/goproject
