# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            belltoy
tagline:          'A Jekyll theme'
description:      'Stuff about programming'
url:              http://belltoy.net
baseurl:          /

author:
  name:           'belltoy'
  url:            https://twitter.com/belltoy

paginate:         15

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/belltoy/belltoy.github.io
